# Type stubs for external dependencies
"""
Minimal type stubs for optional dependencies to improve IDE support
when packages are not installed. These stubs provide basic signatures
for common operations without requiring full package installation.
"""

from typing import Any, Dict, List, Optional, Union, Callable, Iterator


# Stub for rich library
class Console:
    """Rich console for formatted terminal output."""

    def __init__(self, **kwargs: Any) -> None: ...
    def print(self, *args: Any, **kwargs: Any) -> None: ...
    def log(self, *args: Any, **kwargs: Any) -> None: ...
    def rule(self, title: str = "", **kwargs: Any) -> None: ...


class Table:
    """Rich table for formatted data display."""

    def __init__(self, title: Optional[str] = None, **kwargs: Any) -> None: ...
    def add_column(
        self, header: str, justify: str = "left", style: Optional[str] = None, **kwargs: Any
    ) -> None: ...
    def add_row(self, *cells: Any, style: Optional[str] = None) -> None: ...


class Progress:
    """Rich progress bar for long-running operations."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_task(self, description: str, total: Optional[float] = None) -> Any: ...
    def update(self, task_id: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> "Progress": ...
    def __exit__(self, *args: Any) -> None: ...


# Stub for typer
def Typer(*args: Any, **kwargs: Any) -> Any:
    """Typer CLI application."""
    ...


class Argument:
    """Typer command line argument."""

    def __init__(self, default: Any = ..., **kwargs: Any) -> None: ...


class Option:
    """Typer command line option."""

    def __init__(self, default: Any = ..., **kwargs: Any) -> None: ...


# Stub for pydantic
class BaseModel:
    """Pydantic base model for data validation."""

    def __init__(self, **data: Any) -> None: ...
    def dict(self, **kwargs: Any) -> Dict[str, Any]: ...
    def json(self, **kwargs: Any) -> str: ...
    def model_dump(self, **kwargs: Any) -> Dict[str, Any]: ...
    def model_dump_json(self, **kwargs: Any) -> str: ...
    @classmethod
    def model_validate(cls, obj: Any) -> "BaseModel": ...


class Field:
    """Pydantic field with validation."""

    def __init__(self, default: Any = ..., **kwargs: Any) -> None: ...


# Stub for httpx
class Client:
    """HTTPX HTTP client."""

    def __init__(self, **kwargs: Any) -> None: ...
    def get(self, url: str, **kwargs: Any) -> "Response": ...
    def post(self, url: str, **kwargs: Any) -> "Response": ...
    def put(self, url: str, **kwargs: Any) -> "Response": ...
    def delete(self, url: str, **kwargs: Any) -> "Response": ...
    def __enter__(self) -> "Client": ...
    def __exit__(self, *args: Any) -> None: ...


class Response:
    """HTTP response."""

    status_code: int
    text: str
    content: bytes

    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...


# Stub for fastapi
class FastAPI:
    """FastAPI web framework application."""

    def __init__(self, title: str = "", version: str = "", **kwargs: Any) -> None: ...
    def get(self, path: str, **kwargs: Any) -> Callable: ...
    def post(self, path: str, **kwargs: Any) -> Callable: ...
    def put(self, path: str, **kwargs: Any) -> Callable: ...
    def delete(self, path: str, **kwargs: Any) -> Callable: ...


# Stub for numpy (simplified)
class ndarray:
    """NumPy n-dimensional array."""

    shape: tuple
    dtype: Any

    def mean(self) -> float: ...
    def std(self) -> float: ...
    def sum(self) -> float: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...


def array(data: Any, dtype: Any = None) -> ndarray: ...
def mean(data: Any, axis: Any = None) -> Union[float, ndarray]: ...
def std(data: Any, axis: Any = None) -> Union[float, ndarray]: ...
def sum(data: Any, axis: Any = None) -> Union[float, ndarray]: ...
def zeros(shape: Any, dtype: Any = None) -> ndarray: ...
def ones(shape: Any, dtype: Any = None) -> ndarray: ...


# Stub for pandas
class DataFrame:
    """Pandas DataFrame for tabular data."""

    def __init__(self, data: Any = None, columns: Optional[List[str]] = None) -> None: ...
    def to_dict(self, orient: str = "dict") -> Union[Dict, List]: ...
    def to_json(self, orient: str = "columns", **kwargs: Any) -> str: ...
    def to_csv(self, path_or_buf: Any = None, **kwargs: Any) -> Optional[str]: ...
    def head(self, n: int = 5) -> "DataFrame": ...
    def tail(self, n: int = 5) -> "DataFrame": ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __iter__(self) -> Iterator: ...


class Series:
    """Pandas Series for 1-dimensional data."""

    def __init__(self, data: Any = None, index: Any = None, dtype: Any = None) -> None: ...
    def to_list(self) -> List: ...
    def mean(self) -> float: ...
    def std(self) -> float: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
