"""Real-time performance telemetry system with predictive analytics.

This module provides comprehensive monitoring, anomaly detection, and predictive
analytics for evaluation system performance with automated alerting.
"""

import json
import time
import threading
from collections import defaultdict, deque
from dataclasses import dataclass, asdict
from enum import Enum
from typing import Any, Dict, List, Optional, Callable, Tuple
from statistics import mean, stdev
import sqlite3

try:
    import numpy as np
    from scipy import stats
    from sklearn.ensemble import IsolationForest
    from sklearn.preprocessing import StandardScaler
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False

from .enhanced_logging import get_logger

logger = get_logger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class MetricType(Enum):
    """Types of metrics that can be monitored."""
    LATENCY = "latency"
    THROUGHPUT = "throughput"
    ERROR_RATE = "error_rate"
    MEMORY_USAGE = "memory_usage"
    CPU_USAGE = "cpu_usage"
    QUEUE_SIZE = "queue_size"
    WORKER_COUNT = "worker_count"
    CACHE_HIT_RATE = "cache_hit_rate"


@dataclass
class MetricData:
    """Represents a single metric data point."""
    timestamp: float
    metric_name: str
    metric_type: MetricType
    value: float
    tags: Dict[str, str]
    source: str = "unknown"


@dataclass
class Alert:
    """Represents an alert generated by the monitoring system."""
    alert_id: str
    timestamp: float
    severity: AlertSeverity
    metric_name: str
    current_value: float
    threshold: Optional[float]
    message: str
    tags: Dict[str, str]
    resolved: bool = False
    resolved_at: Optional[float] = None


@dataclass
class PerformancePrediction:
    """Represents a performance prediction."""
    timestamp: float
    metric_name: str
    predicted_value: float
    confidence_interval: Tuple[float, float]
    horizon_minutes: int
    model_accuracy: float


class MetricCollector:
    """Collects and aggregates performance metrics."""
    
    def __init__(self, max_history: int = 1000):
        self.max_history = max_history
        self._metrics: Dict[str, deque] = defaultdict(lambda: deque(maxlen=max_history))
        self._lock = threading.RLock()
        self._subscribers: List[Callable[[MetricData], None]] = []
        
    def record(self, metric: MetricData):
        """Record a new metric data point."""
        with self._lock:
            key = f"{metric.metric_name}:{metric.source}"
            self._metrics[key].append(metric)
            
            # Notify subscribers
            for subscriber in self._subscribers:
                try:
                    subscriber(metric)
                except Exception as e:
                    logger.warning(f"Metric subscriber failed: {e}")
    
    def subscribe(self, callback: Callable[[MetricData], None]):
        """Subscribe to metric updates."""
        self._subscribers.append(callback)
    
    def get_recent_metrics(self, metric_name: str, source: Optional[str] = None, limit: int = 100) -> List[MetricData]:
        """Get recent metrics for a specific metric name."""
        with self._lock:
            if source:
                key = f"{metric_name}:{source}"
                if key in self._metrics:
                    return list(self._metrics[key])[-limit:]
            else:
                # Aggregate across all sources
                all_metrics = []
                for key, metrics in self._metrics.items():
                    if key.split(':')[0] == metric_name:
                        all_metrics.extend(metrics)
                
                # Sort by timestamp and return recent ones
                all_metrics.sort(key=lambda m: m.timestamp)
                return all_metrics[-limit:]
            
        return []
    
    def get_summary_stats(self, metric_name: str, window_minutes: int = 5) -> Dict[str, float]:
        """Get summary statistics for a metric within a time window."""
        cutoff_time = time.time() - (window_minutes * 60)
        recent_metrics = []
        
        with self._lock:
            for key, metrics in self._metrics.items():
                if key.split(':')[0] == metric_name:
                    recent_metrics.extend([m for m in metrics if m.timestamp >= cutoff_time])
        
        if not recent_metrics:
            return {}
        
        values = [m.value for m in recent_metrics]
        
        stats = {
            'count': len(values),
            'mean': mean(values),
            'min': min(values),
            'max': max(values),
        }
        
        if len(values) > 1:
            stats['std'] = stdev(values)
            if HAS_SKLEARN:
                stats['p50'] = np.percentile(values, 50)
                stats['p95'] = np.percentile(values, 95)
                stats['p99'] = np.percentile(values, 99)
            else:
                sorted_values = sorted(values)
                stats['p50'] = sorted_values[len(values)//2]
                stats['p95'] = sorted_values[int(len(values)*0.95)]
                stats['p99'] = sorted_values[int(len(values)*0.99)]
        
        return stats


class AnomalyDetector:
    """Detects anomalies in metric data using various algorithms."""
    
    def __init__(self, sensitivity: float = 0.1):
        self.sensitivity = sensitivity
        self._models: Dict[str, Any] = {}
        self._scalers: Dict[str, Any] = {}
        
    def detect_anomalies(self, metrics: List[MetricData]) -> List[MetricData]:
        """Detect anomalies in a list of metrics."""
        if not metrics or not HAS_SKLEARN:
            return []
        
        anomalies = []
        
        # Group metrics by name
        grouped_metrics = defaultdict(list)
        for metric in metrics:
            grouped_metrics[metric.metric_name].append(metric)
        
        for metric_name, metric_list in grouped_metrics.items():
            if len(metric_list) < 10:  # Need minimum samples
                continue
                
            detected = self._detect_statistical_anomalies(metric_list)
            anomalies.extend(detected)
            
            # Use isolation forest if available
            if HAS_SKLEARN:
                ml_detected = self._detect_ml_anomalies(metric_name, metric_list)
                anomalies.extend(ml_detected)
        
        return anomalies
    
    def _detect_statistical_anomalies(self, metrics: List[MetricData]) -> List[MetricData]:
        """Detect anomalies using statistical methods (z-score)."""
        values = [m.value for m in metrics]
        
        if len(values) < 3:
            return []
        
        mean_val = mean(values)
        std_val = stdev(values) if len(values) > 1 else 0
        
        if std_val == 0:
            return []
        
        anomalies = []
        threshold = 3.0  # 3 standard deviations
        
        for metric in metrics:
            z_score = abs((metric.value - mean_val) / std_val)
            if z_score > threshold:
                anomalies.append(metric)
        
        return anomalies
    
    def _detect_ml_anomalies(self, metric_name: str, metrics: List[MetricData]) -> List[MetricData]:
        """Detect anomalies using machine learning (Isolation Forest)."""
        if not HAS_SKLEARN:
            return []
        
        values = np.array([[m.value, m.timestamp] for m in metrics])
        
        # Get or create model for this metric
        if metric_name not in self._models:
            self._models[metric_name] = IsolationForest(contamination=self.sensitivity)
            self._scalers[metric_name] = StandardScaler()
        
        model = self._models[metric_name]
        scaler = self._scalers[metric_name]
        
        # Scale the data
        values_scaled = scaler.fit_transform(values)
        
        # Predict anomalies
        predictions = model.fit_predict(values_scaled)
        
        # Return metrics marked as anomalies (-1)
        anomalies = []
        for i, pred in enumerate(predictions):
            if pred == -1:
                anomalies.append(metrics[i])
        
        return anomalies


class AlertManager:
    """Manages alerts and notifications."""
    
    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or ":memory:"
        self._thresholds: Dict[str, Dict[str, float]] = {}
        self._alert_handlers: List[Callable[[Alert], None]] = []
        self._active_alerts: Dict[str, Alert] = {}
        self._lock = threading.RLock()
        
        self._init_database()
    
    def _init_database(self):
        """Initialize the alert database."""
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS alerts (
                alert_id TEXT PRIMARY KEY,
                timestamp REAL,
                severity TEXT,
                metric_name TEXT,
                current_value REAL,
                threshold REAL,
                message TEXT,
                tags TEXT,
                resolved BOOLEAN,
                resolved_at REAL
            )
        """)
        conn.commit()
        conn.close()
    
    def set_threshold(self, metric_name: str, threshold_type: str, value: float):
        """Set a threshold for a metric."""
        if metric_name not in self._thresholds:
            self._thresholds[metric_name] = {}
        self._thresholds[metric_name][threshold_type] = value
    
    def check_metric(self, metric: MetricData):
        """Check a metric against thresholds and generate alerts if needed."""
        metric_thresholds = self._thresholds.get(metric.metric_name, {})
        
        for threshold_type, threshold_value in metric_thresholds.items():
            alert = self._evaluate_threshold(metric, threshold_type, threshold_value)
            if alert:
                self._trigger_alert(alert)
    
    def _evaluate_threshold(self, metric: MetricData, threshold_type: str, threshold_value: float) -> Optional[Alert]:
        """Evaluate a metric against a specific threshold."""
        triggered = False
        severity = AlertSeverity.WARNING
        
        if threshold_type == "max" and metric.value > threshold_value:
            triggered = True
            severity = AlertSeverity.ERROR if metric.value > threshold_value * 1.5 else AlertSeverity.WARNING
        elif threshold_type == "min" and metric.value < threshold_value:
            triggered = True
            severity = AlertSeverity.ERROR if metric.value < threshold_value * 0.5 else AlertSeverity.WARNING
        
        if triggered:
            alert_id = f"{metric.metric_name}:{threshold_type}:{metric.source}"
            message = f"{metric.metric_name} {threshold_type} threshold exceeded: {metric.value:.2f} vs {threshold_value:.2f}"
            
            return Alert(
                alert_id=alert_id,
                timestamp=metric.timestamp,
                severity=severity,
                metric_name=metric.metric_name,
                current_value=metric.value,
                threshold=threshold_value,
                message=message,
                tags=metric.tags.copy()
            )
        
        return None
    
    def _trigger_alert(self, alert: Alert):
        """Trigger an alert and notify handlers."""
        with self._lock:
            # Check if alert already active
            if alert.alert_id in self._active_alerts:
                # Update existing alert
                self._active_alerts[alert.alert_id].current_value = alert.current_value
                self._active_alerts[alert.alert_id].timestamp = alert.timestamp
            else:
                # New alert
                self._active_alerts[alert.alert_id] = alert
                self._persist_alert(alert)
                
                # Notify handlers
                for handler in self._alert_handlers:
                    try:
                        handler(alert)
                    except Exception as e:
                        logger.error(f"Alert handler failed: {e}")
    
    def resolve_alert(self, alert_id: str):
        """Resolve an active alert."""
        with self._lock:
            if alert_id in self._active_alerts:
                alert = self._active_alerts[alert_id]
                alert.resolved = True
                alert.resolved_at = time.time()
                self._persist_alert(alert)
                del self._active_alerts[alert_id]
    
    def add_alert_handler(self, handler: Callable[[Alert], None]):
        """Add an alert handler."""
        self._alert_handlers.append(handler)
    
    def _persist_alert(self, alert: Alert):
        """Persist alert to database."""
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            INSERT OR REPLACE INTO alerts 
            (alert_id, timestamp, severity, metric_name, current_value, threshold, message, tags, resolved, resolved_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            alert.alert_id, alert.timestamp, alert.severity.value, alert.metric_name,
            alert.current_value, alert.threshold, alert.message, json.dumps(alert.tags),
            alert.resolved, alert.resolved_at
        ))
        conn.commit()
        conn.close()


class PerformancePredictor:
    """Predicts future performance based on historical data."""
    
    def __init__(self):
        self._models: Dict[str, Any] = {}
        self._history_window = 100  # Number of data points to use for prediction
    
    def predict(self, metrics: List[MetricData], horizon_minutes: int = 15) -> List[PerformancePrediction]:
        """Predict future performance for given metrics."""
        if not metrics or not HAS_SKLEARN:
            return []
        
        predictions = []
        
        # Group metrics by name
        grouped_metrics = defaultdict(list)
        for metric in metrics:
            grouped_metrics[metric.metric_name].append(metric)
        
        for metric_name, metric_list in grouped_metrics.items():
            if len(metric_list) < 20:  # Need minimum samples for prediction
                continue
            
            prediction = self._predict_metric(metric_name, metric_list, horizon_minutes)
            if prediction:
                predictions.append(prediction)
        
        return predictions
    
    def _predict_metric(self, metric_name: str, metrics: List[MetricData], horizon_minutes: int) -> Optional[PerformancePrediction]:
        """Predict future values for a specific metric."""
        if not HAS_SKLEARN:
            return None
        
        # Sort by timestamp
        metrics.sort(key=lambda m: m.timestamp)
        
        # Prepare data
        timestamps = np.array([m.timestamp for m in metrics]).reshape(-1, 1)
        values = np.array([m.value for m in metrics])
        
        # Use linear regression for simplicity
        from sklearn.linear_model import LinearRegression
        model = LinearRegression()
        model.fit(timestamps, values)
        
        # Predict future value
        future_time = time.time() + (horizon_minutes * 60)
        predicted_value = model.predict([[future_time]])[0]
        
        # Estimate confidence interval using historical variance
        residuals = values - model.predict(timestamps)
        mse = np.mean(residuals ** 2)
        std_error = np.sqrt(mse)
        
        # 95% confidence interval
        confidence_interval = (
            predicted_value - 1.96 * std_error,
            predicted_value + 1.96 * std_error
        )
        
        # Calculate model accuracy (R²)
        accuracy = model.score(timestamps, values)
        
        return PerformancePrediction(
            timestamp=time.time(),
            metric_name=metric_name,
            predicted_value=predicted_value,
            confidence_interval=confidence_interval,
            horizon_minutes=horizon_minutes,
            model_accuracy=float(accuracy)
        )


class TelemetrySystem:
    """Main telemetry system that coordinates all monitoring components."""
    
    def __init__(self, db_path: Optional[str] = None):
        self.metric_collector = MetricCollector()
        self.anomaly_detector = AnomalyDetector()
        self.alert_manager = AlertManager(db_path)
        self.predictor = PerformancePredictor()
        
        self._monitoring_thread: Optional[threading.Thread] = None
        self._shutdown_event = threading.Event()
        
        # Subscribe to metrics for processing
        self.metric_collector.subscribe(self._process_metric)
    
    def start_monitoring(self, check_interval: float = 10.0):
        """Start the monitoring system."""
        if self._monitoring_thread and self._monitoring_thread.is_alive():
            logger.warning("Monitoring already running")
            return
        
        self._shutdown_event.clear()
        self._monitoring_thread = threading.Thread(
            target=self._monitoring_loop,
            args=(check_interval,),
            daemon=True
        )
        self._monitoring_thread.start()
        logger.info("Telemetry monitoring started")
    
    def stop_monitoring(self):
        """Stop the monitoring system."""
        self._shutdown_event.set()
        if self._monitoring_thread:
            self._monitoring_thread.join(timeout=5.0)
        logger.info("Telemetry monitoring stopped")
    
    def record_metric(self, metric_name: str, value: float, metric_type: MetricType, 
                      tags: Optional[Dict[str, str]] = None, source: str = "system"):
        """Record a performance metric."""
        metric = MetricData(
            timestamp=time.time(),
            metric_name=metric_name,
            metric_type=metric_type,
            value=value,
            tags=tags or {},
            source=source
        )
        self.metric_collector.record(metric)
    
    def get_dashboard_data(self) -> Dict[str, Any]:
        """Get data for performance dashboard."""
        dashboard_data = {}
        
        # Get recent metrics for common performance indicators
        metric_names = ["request_latency", "throughput", "error_rate", "memory_usage"]
        
        for metric_name in metric_names:
            recent_metrics = self.metric_collector.get_recent_metrics(metric_name, limit=50)
            stats = self.metric_collector.get_summary_stats(metric_name, window_minutes=10)
            
            dashboard_data[metric_name] = {
                'recent_values': [{'timestamp': m.timestamp, 'value': m.value} for m in recent_metrics],
                'stats': stats
            }
        
        # Get active alerts
        dashboard_data['active_alerts'] = [
            asdict(alert) for alert in self.alert_manager._active_alerts.values()
        ]
        
        # Get predictions
        all_metrics = []
        for metric_name in metric_names:
            all_metrics.extend(self.metric_collector.get_recent_metrics(metric_name, limit=50))
        
        predictions = self.predictor.predict(all_metrics)
        dashboard_data['predictions'] = [asdict(pred) for pred in predictions]
        
        return dashboard_data
    
    def _process_metric(self, metric: MetricData):
        """Process a new metric data point."""
        # Check for threshold violations
        self.alert_manager.check_metric(metric)
    
    def _monitoring_loop(self, check_interval: float):
        """Main monitoring loop."""
        while not self._shutdown_event.is_set():
            try:
                # Periodic anomaly detection
                self._run_anomaly_detection()
                
                # Auto-resolve stale alerts
                self._check_stale_alerts()
                
            except Exception as e:
                logger.error(f"Monitoring loop error: {e}")
            
            self._shutdown_event.wait(check_interval)
    
    def _run_anomaly_detection(self):
        """Run anomaly detection on recent metrics."""
        # Get recent metrics from last 30 minutes
        cutoff_time = time.time() - (30 * 60)
        recent_metrics = []
        
        for key, metrics in self.metric_collector._metrics.items():
            recent_metrics.extend([m for m in metrics if m.timestamp >= cutoff_time])
        
        if recent_metrics:
            anomalies = self.anomaly_detector.detect_anomalies(recent_metrics)
            
            for anomaly in anomalies:
                # Create anomaly alert
                alert = Alert(
                    alert_id=f"anomaly:{anomaly.metric_name}:{anomaly.timestamp}",
                    timestamp=anomaly.timestamp,
                    severity=AlertSeverity.WARNING,
                    metric_name=anomaly.metric_name,
                    current_value=anomaly.value,
                    threshold=None,
                    message=f"Anomaly detected in {anomaly.metric_name}: {anomaly.value}",
                    tags=anomaly.tags.copy()
                )
                self.alert_manager._trigger_alert(alert)
    
    def _check_stale_alerts(self):
        """Check for stale alerts and auto-resolve them."""
        current_time = time.time()
        stale_threshold = 300  # 5 minutes
        
        for alert_id, alert in list(self.alert_manager._active_alerts.items()):
            if current_time - alert.timestamp > stale_threshold:
                self.alert_manager.resolve_alert(alert_id)
                logger.info(f"Auto-resolved stale alert: {alert_id}")


# Default alert handlers
def console_alert_handler(alert: Alert):
    """Simple console alert handler."""
    severity_colors = {
        AlertSeverity.INFO: '\033[94m',
        AlertSeverity.WARNING: '\033[93m',
        AlertSeverity.ERROR: '\033[91m',
        AlertSeverity.CRITICAL: '\033[95m'
    }
    reset_color = '\033[0m'
    
    color = severity_colors.get(alert.severity, '')
    print(f"{color}[ALERT {alert.severity.value.upper()}]{reset_color} {alert.message}")


def log_alert_handler(alert: Alert):
    """Log-based alert handler."""
    if alert.severity == AlertSeverity.CRITICAL:
        logger.critical(f"ALERT: {alert.message}")
    elif alert.severity == AlertSeverity.ERROR:
        logger.error(f"ALERT: {alert.message}")
    elif alert.severity == AlertSeverity.WARNING:
        logger.warning(f"ALERT: {alert.message}")
    else:
        logger.info(f"ALERT: {alert.message}")