"""Package initialization for code explainers.

Provides main API for code explanation functionality.
"""

from .async_explainer import AsyncExplainer
from .base import (
    CodeAnalyzer,
    CodeExplainer,
    ComplexityAnalyzer,
    ExplainerRegistry,
    ExplanationEvaluator,
    ExplanationFormatter,
    get_global_registry,
)
from .batch_processor import (
    BatchItem,
    BatchProcessor,
    BatchResult,
    BatchStatus,
    ConcurrencyLimiter,
    ExplainerBatchProcessor,
    run_batch_async,
)
from .cache_backends import MemcachedCacheManager, RedisCacheManager
from .cache_manager import CacheManager, InMemoryCacheManager, NoOpCacheManager
from .chain import ChainStrategy, ExplainerChain
from .cli_commands import ExplainerCLI, get_explainer_cli
from .diff_explainer import (
    ChangeSignificance,
    DiffLine,
    DiffSection,
    DiffTracker,
    DiffType,
    ExplanationDiff,
    compare_explanation_texts,
    compare_explanations,
    get_diff_tracker,
)
from .event_hooks import (
    EventEmitter,
    EventSubscriber,
    ExplainerEvent,
    ExplainerEventType,
    get_event_emitter,
    get_event_subscriber,
)
from .factory import ExplainerFactory, get_explainer_factory
from .health_check import (
    ComponentHealth,
    HealthChecker,
    HealthStatus,
    SystemHealth,
    create_cache_health_check,
    create_explainer_health_check,
    create_memory_health_check,
    get_health_checker,
)
from .metrics_plugin import (
    ClarityMetric,
    CompletenessMetric,
    ConcisennessMetric,
    MetricsRegistry,
    QualityMetric,
    get_metrics_registry,
)
from .middleware import (
    CachingMiddleware,
    EnrichmentMiddleware,
    ExplainerMiddleware,
    LoggingMiddleware,
    MiddlewareChain,
    ValidationMiddleware,
)
from .model_selector import ModelSelector
from .prompt_templates import (
    ChainOfThoughtPromptTemplate,
    DirectPromptTemplate,
    ExpertPromptTemplate,
    PromptStyle,
    PromptTemplate,
    PromptTemplateManager,
    SocraticPromptTemplate,
)
from .retry_policy import (
    RetryableExplainer,
    RetryConfig,
    RetryPolicy,
    RetryResult,
    RetryStrategy,
    get_retry_config,
    retry_decorator,
)
from .types import (
    AnalysisResult,
    CodeElement,
    CodeElementType,
    ComplexityMetrics,
    ExplainLevel,
    ExplanationResult,
)
from .versioning import (
    ExplanationVersion,
    VersionedExplainer,
    VersionTracker,
    get_version_tracker,
)
from .caching_decorators import (
    CacheEntry,
    CacheNamespace,
    CacheStats,
    ExplainerCache,
    LRUCache,
    async_cache,
    cache,
    conditional_cache,
    get_explainer_cache,
    memoize,
    reset_explainer_cache,
)
from .rate_limiter import (
    ExplainerRateLimiter,
    FixedWindowLimiter,
    LeakyBucketLimiter,
    RateLimitConfig,
    RateLimitExceeded,
    RateLimiter,
    RateLimiterGroup,
    RateLimitStatus,
    RateLimitStrategy,
    SlidingWindowLimiter,
    TokenBucketLimiter,
    async_rate_limit,
    create_rate_limiter,
    get_explainer_rate_limiter,
    rate_limit,
    reset_explainer_rate_limiter,
)
from .config_presets import (
    CacheConfig,
    CacheMode,
    Environment,
    ExplainerConfig,
    LoggingConfig,
    LogLevel,
    MetricsConfig,
    ModelConfig,
    RateLimitPreset,
    RetryPreset,
    budget_config,
    create_config,
    development_config,
    get_config_for_environment,
    get_preset,
    high_throughput_config,
    list_presets,
    low_latency_config,
    production_config,
    register_preset,
    staging_config,
    testing_config,
)
from .telemetry import (
    ExplainerTelemetry,
    InMemoryBackend,
    LatencyStats,
    LoggingBackend,
    MetricType,
    MetricValue,
    TelemetryBackend,
    TelemetryExporter,
    ThroughputStats,
    UsageStats,
    async_timed,
    get_telemetry,
    reset_telemetry,
    timed,
)
from .explanation_templates import (
    ClassTemplate,
    ExplanationTemplate,
    FunctionTemplate,
    LoopTemplate,
    PatternMatch,
    PatternType,
    TemplateRegistry,
    TemplateSection,
    generate_from_template,
    get_template_registry,
)
from .streaming_explainer import (
    ChunkedStreamingExplainer,
    SectionStreamingExplainer,
    StreamChunk,
    StreamEventType,
    StreamingExplainer,
    StreamMultiplexer,
    StreamProgress,
    StreamResult,
    WordStreamingExplainer,
    create_streaming_explainer,
    stream_to_callback,
    stream_to_callback_async,
)
from .pipeline import (
    BranchStage,
    ConditionalPipeline,
    EnrichmentStage,
    ExplainerPipeline,
    ExplainerStage,
    FilterStage,
    ParallelPipeline,
    Pipeline,
    PipelineResult,
    PipelineStage,
    StageResult,
    StageStatus,
    TransformStage,
    ValidateStage,
    compose,
    create_pipeline,
)
from .result_aggregator import (
    AggregatedResult,
    AggregationStats,
    AggregationStrategy,
    AggregatorComparison,
    BulkAggregator,
    ComparisonResult,
    ExplanationAggregator,
    GroupedStats,
    ResultAggregator,
    ResultCollector,
    StatsReporter,
    aggregate_results,
    collect_results,
    compute_result_stats,
    create_reporter,
    get_default_collector,
    merge_explanations,
    reset_default_collector,
)
from .ab_testing import (
    ABTestingManager,
    Assignment,
    AssignmentStrategy,
    Experiment,
    ExperimentConfig,
    ExperimentReporter,
    ExperimentResult,
    ExperimentRunner,
    ExperimentStatus,
    ExperimentSummary,
    FeatureFlag,
    HashAssigner,
    RandomAssigner,
    RoundRobinAssigner,
    StickyAssigner,
    Variant,
    VariantAssigner,
    VariantStats,
    VariantType,
    create_experiment,
    get_ab_testing_manager,
    reset_ab_testing_manager,
    run_ab_test,
)
from .cost_tracker import (
    Budget,
    BudgetStatus,
    CostBackend,
    CostContext,
    CostEntry,
    CostReporter,
    CostSummary,
    CostTracker,
    CostType,
    CostUnit,
    InMemoryCostBackend,
    PricingTier,
    TokenUsage,
    create_cost_tracker,
    get_cost_tracker,
    reset_cost_tracker,
    track_cost,
)
from .quality_analyzer import (
    BatchQualityAnalyzer,
    BatchQualityStats,
    ClarityMetric as QAClarityMetric,
    CoherenceMetric,
    CompletenessMetric as QACompletenessMetric,
    ConcisenessMetric as QAConcisenessMetric,
    QualityAnalyzer,
    QualityDimension,
    QualityGate,
    QualityLevel,
    QualityMetric as QAMetric,
    QualityReport,
    QualityScore,
    QualityThreshold,
    RelevanceMetric,
    analyze_quality,
    check_quality,
    create_analyzer,
    create_quality_gate,
)
from .doc_generator import (
    DocConfig,
    DocElement,
    DocFormat,
    DocFormatter,
    DocGenerator,
    DocSection,
    DocstringFormatter,
    DocstringGenerator,
    DocWriter,
    GeneratedDoc,
    HTMLFormatter,
    MarkdownFormatter,
    RSTFormatter,
    create_doc_generator,
    generate_docstring,
    generate_html,
    generate_markdown,
)
from .integration_adapters import (
    AdapterConfig,
    AdapterRegistry,
    FileSystemAdapter,
    GitHubAdapter,
    GitLabAdapter,
    IntegrationAdapter,
    IntegrationManager,
    IntegrationResult,
    IntegrationType,
    JSONAdapter,
    JUnitAdapter,
    OutputFormat,
    SARIFAdapter,
    VSCodeAdapter,
    WebhookAdapter,
    create_adapter,
    export_to_github,
    export_to_gitlab,
    export_to_json,
    export_to_sarif,
    get_integration_manager,
    reset_integration_manager,
)
from .context_provider import (
    ContextItem,
    ContextManager,
    ContextPriority,
    ContextProvider,
    ContextResult,
    ContextScope,
    ContextType,
    DocumentationContextProvider,
    FileContext,
    FileContextProvider,
    GitContext,
    GitContextProvider,
    ProjectContext,
    ProjectContextProvider,
    ProviderConfig,
    UsageContextProvider,
    create_context_provider,
    gather_context,
    get_context_manager,
    reset_context_manager,
)
from .explanation_validator import (
    BatchValidator,
    CodeReferenceChecker,
    CompletenessChecker,
    ConsistencyChecker,
    ExplanationValidator,
    HallucinationDetector,
    IssueSeverity,
    IssueType,
    TerminologyChecker,
    ValidationCheck,
    ValidationIssue,
    ValidationLevel,
    ValidationResult,
    ValidationRule,
    ValidationStatus,
    ValidatorConfig,
    create_validator,
    get_validator,
    reset_validator,
    validate_explanation,
)
from .language_support import (
    DetectionResult,
    JavaScriptParser,
    Language,
    LanguageConfig,
    LanguageDetector,
    LanguageFamily,
    LanguageFeatures,
    LanguageParser,
    MultiLanguageExplainer,
    ParsedElement,
    PythonParser,
    detect_language,
    get_language_detector,
    get_language_features,
    get_multi_language_explainer,
    reset_language_detector,
    reset_multi_language_explainer,
)
from .semantic_cache import (
    CachedExplanation,
    CacheHitType,
    CacheKeyGenerator,
    CacheLookupResult,
    CacheStatistics,
    CacheStorage,
    CacheStrategy,
    CacheWarmer,
    CombinedSimilarityCalculator,
    EditDistanceSimilarityCalculator,
    InMemoryStorage,
    InvalidationPolicy,
    SemanticCache,
    SemanticCacheConfig,
    SimilarityCalculator,
    StructuralSimilarityCalculator,
    TokenSimilarityCalculator,
    cache_lookup,
    cache_store,
    create_semantic_cache,
    get_semantic_cache,
    reset_semantic_cache,
)
from .feedback_collector import (
    FeedbackAggregation,
    FeedbackAnalyzer,
    FeedbackCategory,
    FeedbackCollector,
    FeedbackCollectorConfig,
    FeedbackExporter,
    FeedbackItem,
    FeedbackReport,
    FeedbackSentiment,
    FeedbackStatus,
    FeedbackStorage,
    FeedbackType,
    InMemoryFeedbackStorage,
    collect_rating,
    collect_thumbs,
    create_feedback_collector,
    get_feedback_collector,
    reset_feedback_collector,
)
from .explanation_comparator import (
    BatchComparisonResult,
    ComparisonMetric,
    ComparisonResult as DeepComparisonResult,
    ComparisonScores,
    ComparisonStrategy,
    ComparisonType,
    ComparatorConfig,
    CoverageComparisonStrategy,
    Difference,
    DifferenceType,
    ExplanationComparator,
    LexicalComparisonStrategy,
    ModelComparator,
    SignificanceLevel,
    StructuralComparisonStrategy,
    TechnicalComparisonStrategy,
    TopicAnalysis,
    VersionComparator,
    compare_explanations as deep_compare_explanations,
    compare_texts,
    create_comparator,
    get_comparator,
    reset_comparator,
)

__all__ = [
    # Async support
    "AsyncExplainer",
    # Batch processing
    "BatchItem",
    "BatchProcessor",
    "BatchResult",
    "BatchStatus",
    "ConcurrencyLimiter",
    "ExplainerBatchProcessor",
    "run_batch_async",
    # Base classes
    "CodeAnalyzer",
    "CodeExplainer",
    "ComplexityAnalyzer",
    "ExplanationFormatter",
    "ExplanationEvaluator",
    "ExplainerRegistry",
    # Cache management
    "CacheManager",
    "InMemoryCacheManager",
    "NoOpCacheManager",
    "RedisCacheManager",
    "MemcachedCacheManager",
    # Diff system
    "ChangeSignificance",
    "DiffLine",
    "DiffSection",
    "DiffTracker",
    "DiffType",
    "ExplanationDiff",
    "compare_explanations",
    "compare_explanation_texts",
    "get_diff_tracker",
    # Explainer chaining
    "RedisCacheManager",
    "MemcachedCacheManager",
    # Explainer chaining
    "ExplainerChain",
    "ChainStrategy",
    # Event system
    "ExplainerEvent",
    "ExplainerEventType",
    "EventEmitter",
    "EventSubscriber",
    "get_event_emitter",
    "get_event_subscriber",
    # Factory
    "ExplainerFactory",
    "get_explainer_factory",
    # Health check
    "HealthChecker",
    "HealthStatus",
    "ComponentHealth",
    "SystemHealth",
    "create_explainer_health_check",
    "create_cache_health_check",
    "create_memory_health_check",
    "get_health_checker",
    # CLI
    "ExplainerCLI",
    "get_explainer_cli",
    # Quality metrics
    "QualityMetric",
    "ClarityMetric",
    "CompletenessMetric",
    "ConcisennessMetric",
    "MetricsRegistry",
    "get_metrics_registry",
    # Middleware
    "ExplainerMiddleware",
    "LoggingMiddleware",
    "ValidationMiddleware",
    "EnrichmentMiddleware",
    "CachingMiddleware",
    "MiddlewareChain",
    # Model selection
    "ModelSelector",
    # Prompt templates
    "PromptStyle",
    "PromptTemplate",
    "PromptTemplateManager",
    "DirectPromptTemplate",
    "ChainOfThoughtPromptTemplate",
    "SocraticPromptTemplate",
    "ExpertPromptTemplate",
    # Retry policy
    "RetryConfig",
    "RetryPolicy",
    "RetryResult",
    "RetryStrategy",
    "RetryableExplainer",
    "retry_decorator",
    "get_retry_config",
    # Versioning
    "ExplanationVersion",
    "VersionTracker",
    "VersionedExplainer",
    "get_version_tracker",
    # Caching decorators
    "CacheEntry",
    "CacheNamespace",
    "CacheStats",
    "ExplainerCache",
    "LRUCache",
    "async_cache",
    "cache",
    "conditional_cache",
    "get_explainer_cache",
    "memoize",
    "reset_explainer_cache",
    # Rate limiting
    "ExplainerRateLimiter",
    "FixedWindowLimiter",
    "LeakyBucketLimiter",
    "RateLimitConfig",
    "RateLimitExceeded",
    "RateLimiter",
    "RateLimiterGroup",
    "RateLimitStatus",
    "RateLimitStrategy",
    "SlidingWindowLimiter",
    "TokenBucketLimiter",
    "async_rate_limit",
    "create_rate_limiter",
    "get_explainer_rate_limiter",
    "rate_limit",
    "reset_explainer_rate_limiter",
    # Configuration presets
    "CacheConfig",
    "CacheMode",
    "Environment",
    "ExplainerConfig",
    "LoggingConfig",
    "LogLevel",
    "MetricsConfig",
    "ModelConfig",
    "RateLimitPreset",
    "RetryPreset",
    "budget_config",
    "create_config",
    "development_config",
    "get_config_for_environment",
    "get_preset",
    "high_throughput_config",
    "list_presets",
    "low_latency_config",
    "production_config",
    "register_preset",
    "staging_config",
    "testing_config",
    # Telemetry
    "ExplainerTelemetry",
    "InMemoryBackend",
    "LatencyStats",
    "LoggingBackend",
    "MetricType",
    "MetricValue",
    "TelemetryBackend",
    "TelemetryExporter",
    "ThroughputStats",
    "UsageStats",
    "async_timed",
    "get_telemetry",
    "reset_telemetry",
    "timed",
    # Explanation templates
    "ClassTemplate",
    "ExplanationTemplate",
    "FunctionTemplate",
    "LoopTemplate",
    "PatternMatch",
    "PatternType",
    "TemplateRegistry",
    "TemplateSection",
    "generate_from_template",
    "get_template_registry",
    # Streaming explainers
    "ChunkedStreamingExplainer",
    "SectionStreamingExplainer",
    "StreamChunk",
    "StreamEventType",
    "StreamingExplainer",
    "StreamMultiplexer",
    "StreamProgress",
    "StreamResult",
    "WordStreamingExplainer",
    "create_streaming_explainer",
    "stream_to_callback",
    "stream_to_callback_async",
    # Pipeline system
    "BranchStage",
    "ConditionalPipeline",
    "EnrichmentStage",
    "ExplainerPipeline",
    "ExplainerStage",
    "FilterStage",
    "ParallelPipeline",
    "Pipeline",
    "PipelineResult",
    "PipelineStage",
    "StageResult",
    "StageStatus",
    "TransformStage",
    "ValidateStage",
    "compose",
    "create_pipeline",
    # Result aggregation
    "AggregatedResult",
    "AggregationStats",
    "AggregationStrategy",
    "AggregatorComparison",
    "BulkAggregator",
    "ComparisonResult",
    "ExplanationAggregator",
    "GroupedStats",
    "ResultAggregator",
    "ResultCollector",
    "StatsReporter",
    "aggregate_results",
    "collect_results",
    "compute_result_stats",
    "create_reporter",
    "get_default_collector",
    "merge_explanations",
    "reset_default_collector",
    # A/B testing
    "ABTestingManager",
    "Assignment",
    "AssignmentStrategy",
    "Experiment",
    "ExperimentConfig",
    "ExperimentReporter",
    "ExperimentResult",
    "ExperimentRunner",
    "ExperimentStatus",
    "ExperimentSummary",
    "FeatureFlag",
    "HashAssigner",
    "RandomAssigner",
    "RoundRobinAssigner",
    "StickyAssigner",
    "Variant",
    "VariantAssigner",
    "VariantStats",
    "VariantType",
    "create_experiment",
    "get_ab_testing_manager",
    "reset_ab_testing_manager",
    "run_ab_test",
    # Cost tracking
    "Budget",
    "BudgetStatus",
    "CostBackend",
    "CostContext",
    "CostEntry",
    "CostReporter",
    "CostSummary",
    "CostTracker",
    "CostType",
    "CostUnit",
    "InMemoryCostBackend",
    "PricingTier",
    "TokenUsage",
    "create_cost_tracker",
    "get_cost_tracker",
    "reset_cost_tracker",
    "track_cost",
    # Quality analysis
    "BatchQualityAnalyzer",
    "BatchQualityStats",
    "QAClarityMetric",
    "CoherenceMetric",
    "QACompletenessMetric",
    "QAConcisenessMetric",
    "QualityAnalyzer",
    "QualityDimension",
    "QualityGate",
    "QualityLevel",
    "QAMetric",
    "QualityReport",
    "QualityScore",
    "QualityThreshold",
    "RelevanceMetric",
    "analyze_quality",
    "check_quality",
    "create_analyzer",
    "create_quality_gate",
    # Documentation generation
    "DocConfig",
    "DocElement",
    "DocFormat",
    "DocFormatter",
    "DocGenerator",
    "DocSection",
    "DocstringFormatter",
    "DocstringGenerator",
    "DocWriter",
    "GeneratedDoc",
    "HTMLFormatter",
    "MarkdownFormatter",
    "RSTFormatter",
    "create_doc_generator",
    "generate_docstring",
    "generate_html",
    "generate_markdown",
    # Integration adapters
    "AdapterConfig",
    "AdapterRegistry",
    "FileSystemAdapter",
    "GitHubAdapter",
    "GitLabAdapter",
    "IntegrationAdapter",
    "IntegrationManager",
    "IntegrationResult",
    "IntegrationType",
    "JSONAdapter",
    "JUnitAdapter",
    "OutputFormat",
    "SARIFAdapter",
    "VSCodeAdapter",
    "WebhookAdapter",
    "create_adapter",
    "export_to_github",
    "export_to_gitlab",
    "export_to_json",
    "export_to_sarif",
    "get_integration_manager",
    "reset_integration_manager",
    # Context providers
    "ContextItem",
    "ContextManager",
    "ContextPriority",
    "ContextProvider",
    "ContextResult",
    "ContextScope",
    "ContextType",
    "DocumentationContextProvider",
    "FileContext",
    "FileContextProvider",
    "GitContext",
    "GitContextProvider",
    "ProjectContext",
    "ProjectContextProvider",
    "ProviderConfig",
    "UsageContextProvider",
    "create_context_provider",
    "gather_context",
    "get_context_manager",
    "reset_context_manager",
    # Explanation validation
    "BatchValidator",
    "CodeReferenceChecker",
    "CompletenessChecker",
    "ConsistencyChecker",
    "ExplanationValidator",
    "HallucinationDetector",
    "IssueSeverity",
    "IssueType",
    "TerminologyChecker",
    "ValidationCheck",
    "ValidationIssue",
    "ValidationLevel",
    "ValidationResult",
    "ValidationRule",
    "ValidationStatus",
    "ValidatorConfig",
    "create_validator",
    "get_validator",
    "reset_validator",
    "validate_explanation",
    # Language support
    "DetectionResult",
    "JavaScriptParser",
    "Language",
    "LanguageConfig",
    "LanguageDetector",
    "LanguageFamily",
    "LanguageFeatures",
    "LanguageParser",
    "MultiLanguageExplainer",
    "ParsedElement",
    "PythonParser",
    "detect_language",
    "get_language_detector",
    "get_language_features",
    "get_multi_language_explainer",
    "reset_language_detector",
    "reset_multi_language_explainer",
    # Semantic caching
    "CachedExplanation",
    "CacheHitType",
    "CacheKeyGenerator",
    "CacheLookupResult",
    "CacheStatistics",
    "CacheStorage",
    "CacheStrategy",
    "CacheWarmer",
    "CombinedSimilarityCalculator",
    "EditDistanceSimilarityCalculator",
    "InMemoryStorage",
    "InvalidationPolicy",
    "SemanticCache",
    "SemanticCacheConfig",
    "SimilarityCalculator",
    "StructuralSimilarityCalculator",
    "TokenSimilarityCalculator",
    "cache_lookup",
    "cache_store",
    "create_semantic_cache",
    "get_semantic_cache",
    "reset_semantic_cache",
    # Feedback collection
    "FeedbackAggregation",
    "FeedbackAnalyzer",
    "FeedbackCategory",
    "FeedbackCollector",
    "FeedbackCollectorConfig",
    "FeedbackExporter",
    "FeedbackItem",
    "FeedbackReport",
    "FeedbackSentiment",
    "FeedbackStatus",
    "FeedbackStorage",
    "FeedbackType",
    "InMemoryFeedbackStorage",
    "collect_rating",
    "collect_thumbs",
    "create_feedback_collector",
    "get_feedback_collector",
    "reset_feedback_collector",
    # Explanation comparison
    "BatchComparisonResult",
    "ComparisonMetric",
    "DeepComparisonResult",
    "ComparisonScores",
    "ComparisonStrategy",
    "ComparisonType",
    "ComparatorConfig",
    "CoverageComparisonStrategy",
    "Difference",
    "DifferenceType",
    "ExplanationComparator",
    "LexicalComparisonStrategy",
    "ModelComparator",
    "SignificanceLevel",
    "StructuralComparisonStrategy",
    "TechnicalComparisonStrategy",
    "TopicAnalysis",
    "VersionComparator",
    "deep_compare_explanations",
    "compare_texts",
    "create_comparator",
    "get_comparator",
    "reset_comparator",
    # Type definitions
    "CodeElement",
    "CodeElementType",
    "ExplainLevel",
    "ExplanationResult",
    "AnalysisResult",
    "ComplexityMetrics",
    # Registry
    "get_global_registry",
]

__doc__ = """OpenEval Code Explainers

Modular, extensible system for generating and evaluating code explanations.

Quick Start:
    from openeval.explainers import CodeExplainer, get_global_registry

    # Get a registered explainer
    registry = get_global_registry()
    explainer_class = registry.get_explainer('llm')
    explainer = explainer_class()

    # Or use directly if available
    from openeval.explainers.ast_analyzer import PythonASTAnalyzer
    analyzer = PythonASTAnalyzer()
    analysis = analyzer.analyze(code_string)

Core Interfaces:
    - CodeAnalyzer: Parse and analyze code structure
    - CodeExplainer: Generate explanations for code elements
    - ComplexityAnalyzer: Compute code metrics
    - ExplanationFormatter: Format explanations for display
    - ExplanationEvaluator: Score explanation quality

Data Types:
    - CodeElement: Represents a code element (function, class, etc)
    - ExplanationResult: Result of explaining a code element
    - AnalysisResult: Result of analyzing code structure
    - ComplexityMetrics: Computed code metrics

See: docs/explainers.md for architecture and examples
"""
